name = "book"
version = "0.1.0"
defaultTargets = ["book"]

[[lean_lib]]
name = "Book"

[leanOptions]
autoImplicit = false
pp.unicode.fun=true

# [[require]]
# name = "mathlib"
# scope = "leanprover-community"
# rev = "v4.17.0"

[[lean_exe]]
name = "book"
root = "Main"
